name: Github CI

on:
  push:
  pull_request:

jobs:
  prepare:
    name: Prepare and build code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: target-build
          path: ./target
          retention-days: 1
          if-no-files-found: error

  attach-release:
    name: Attach built code to release
    runs-on: ubuntu-latest
    needs: prepare
    # If this is a tag push
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download target
        uses: actions/download-artifact@v2
        with:
          name: target-build
          path: ./target/**

      - name: Added built files to latest release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: target/sink-library*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  javadocs:
    name: Update javadocs
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download target
        uses: actions/download-artifact@v2
        with:
          name: target-build
          path: ./target/**

      - name: Commit generated javadocs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/main')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/apidocs

  finish:
    name: Finish ci
    runs-on: ubuntu-latest
    needs: [javadocs, attach-release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download target
        uses: actions/download-artifact@v2
        with:
          name: target-build
          if-no-files-found: error
          path: ./target/**

      - name: Upload built jar
        uses: actions/upload-artifact@v2
        with:
          name: jar-build
          if-no-files-found: error
          path: target/sink-library*.jar

      - name: Delete target-build
        uses: geekyeggo/delete-artifact@v1
        with:
          name: target-build
