name: Maven CI

on:
  push:
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    paths:
      - '**.java'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    name: Prepare and build code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2.3.0
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build maven code
        run: mvn --batch-mode package

      - name: Test maven code
        run: mvn --batch-mode test

      - name: Added built files to latest release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        # If this is a tag push
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: ./target/sink-library*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload built jar
        uses: actions/upload-artifact@v2
        with:
          name: target-build
          if-no-files-found: error
          path: |
            ./target/sink-library*.jar
