name: Build Maven Project

on:
  push:
  pull_request:

jobs:
  prepare:
    name: Setup Java and Build code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'

      - name: Install with maven
        run: mvn --batch-mode --update-snapshots clean install

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Added built files to latest release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        # If this is a tag push
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: target/sink-library*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated javadocs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/main')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/apidocs

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          if-no-files-found: error
          path: |
            target/sink-library*.jar
