name: Build Maven Project

on:
  push:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '8'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package
  
  attach:
    name: Attach built files to latest release
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Added built files to latest release
        if: startsWith(github.ref, 'refs/tags/')
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: target/sink-library-v*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pages:
    name: Commit generated javadocs to gh-pages branch
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Publish t 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/apidocs

  artifact:
    name: Upload artifacts
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Upload jar artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          if-no-files-found: error
          path: |
            target/sink-library-v*.jar

