name: Maven CI

on:
  push:
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    paths:
      - '**.java'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    name: Build and test ${{ matrix.spigot }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # See versions: https://hub.spigotmc.org/nexus/#view-repositories;snapshots~browsestorage
        # See most used versions https://minecraft-statistic.net/en/global_statistic.html
        # This can change at any moment, if you want <3
        spigot:
          - 1.17.1-R0.1-SNAPSHOT
          - 1.16.5-R0.1-SNAPSHOT
          - 1.12.2-R0.1-SNAPSHOT
          - 1.8.8-R0.1-SNAPSHOT

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3.8.0
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test code with ${{ matrix.spigot }}
        run: mvn --batch-mode test "-Dspigot.version=${{ matrix.spigot }}"

      - name: Build code with ${{ matrix.spigot }}
        run: mvn --batch-mode package "-Dspigot.version=${{ matrix.spigot }}"

      - name: Upload built jar
        uses: actions/upload-artifact@v2
        with:
          name: target=${{ matrix.spigot }}-build
          if-no-files-found: error
          path: |
            ./target/sink-library*.jar
